apiVersion: v1
kind: Pod
metadata:
  name: doge-pod
spec:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  containers:
  - name: main
    image: main:latest
    command:
    - cat
    tty: true
    resources:
      requests:
        cpu: 2500m
        memory: 5Gi
      limits:
        cpu: 3200m
        memory: 7Gi
    env:
    - name: "NODE_OPTIONS"
      value: "--max-old-space-size=7000"
